# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-12 08:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='category',
            field=models.IntegerField(default=0),
        ),
    ]
